version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '8055:3000'
    networks:
      - traefik
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.home`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  traefik:
    name: traefik_default
    external: true

volumes:
    grafana_data: {}
