version: "3.8"

services:
  adguard:
    image: adguard/adguardhome
    container_name: "adguard"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '68:68/tcp'
      - '68:68/udp'
      #- '80:80/tcp'
      #- '443:443/tcp'
      - '784:784/udp'
      - '853:853/tcp'
      - '853:853/udp'
      - '3001:3000/tcp' # WebUI for installation
      - '5443:5443/tcp'
      - '5443:5443/udp'
      - '8053:80/tcp'
      - '8853:8853/udp'
    networks:
        - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.entrypoints=http"
      - "traefik.http.routers.adguard.rule=Host(`adguard.home`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"

networks:
    traefik:
        name: traefik_default
        external: true
