version: "3.8"

services:
  adguard:
    image: adguard/adguardhome
    container_name: "adguard"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      #- '80:80/tcp'
      #- '443:443/tcp'
      - '8053:80/tcp'
      - '853:853/tcp'
      - '3000:3000/tcp'
    networks:
        - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.entrypoints=http"
      - "traefik.http.routers.adguard.rule=Host(`adguard.home`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
