version: "3.8"

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: "dozzle"
    restart: unless-stopped
    ports:
      - '8054:80'
    networks:
        - traefik
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.entrypoints=http"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.home`)"
      - "traefik.http.services.dozzle.loadbalancer.server.port=80"

networks:
    traefik:
        name: traefik_default
        external: true
