version: "3.8"

services:
  gitea:
    image: gitea/gitea:1.20.4-rootless
    container_name: "gitea"
    restart: unless-stopped
    ports:
      - '8057:3000'
      - '8058:2222'
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea_01.entrypoints=http"
      - "traefik.http.routers.gitea_01.rule=Host(`git.home`)"
      - "traefik.http.services.gitea_01.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea_02.entrypoints=ssh"
      - "traefik.http.routers.gitea_02.rule=Host(`git.home`)"
      - "traefik.http.services.gitea_02.loadbalancer.server.port=2222"

  db:
    image: postgres:14
    container_name: "gitea-db"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  traefik:
    name: traefik_default
    external: true

volumes:
  gitea-data:
    driver: local
  gitea-config:
    driver: local
