version: "3.8"

services:
  gitea:
    image: gitea/gitea:1.20.4-rootless
    container_name: "gitea"
    restart: unless-stopped
    ports:
      - '8057:3000'
      - '8058:2222'
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea
      - traefik
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: db:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea
    depends_on:
      - db
    links:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea-http.entrypoints=http"
      - "traefik.http.routers.gitea-http.service=gitea-http"
      - "traefik.http.routers.gitea-http.rule=Host(`git.home`)"
      - "traefik.http.services.gitea-http.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh"
      - "traefik.tcp.routers.gitea-ssh.rule=Host(`git.home`)"
      - "traefik.tcp.services.gitea-ssh.loadbalancer.server.port=2222"
      - "traefik.docker.network=gitea"

  db:
    image: postgres:14
    container_name: "gitea-db"
    restart: unless-stopped
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - gitea-db:/var/lib/postgresql/data
    networks:
      - gitea

networks:
  gitea:
    name: gitea_default
    external: false
  traefik:
    name: traefik_default
    external: true

volumes:
  gitea-data:
    driver: local
  gitea-config:
    driver: local
  gitea-db:
    driver: local
