version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: "traefik"
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - target: 80 # HTTP
        published: 80
        protocol: tcp
        mode: host
      - target: 443 # HTTPS
        published: 443
        protocol: tcp
        mode: host
      - target: 8080 # Dashboard. Fine for home server, a big no-no for production
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-ssl-certs:/ssl-certs
      - /home/danaketh/homelab/stacks/traefik/etc/traefik.yml:/etc/traefik/traefik.yml
    networks:
        - traefik

networks:
    traefik:
        name: traefik_default
        external: true

volumes:
    traefik-ssl-certs:
        driver: local
