version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: "traefik"
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # Fine for home server, a big no-no for production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-ssl-certs:/ssl-certs
      - /home/danaketh/homelab/stacks/traefik/etc/traefik.yml:/etc/traefik/traefik.yml
    networks:
        - traefik

networks:
    traefik:
        name: traefik_default
        external: true

volumes:
    traefik-ssl-certs:
        driver: local
